site_name: Lost Mapper
site_url: https://lostmapper.com/
site_description: Wandering in the world of map-making, cartography and GIS
theme:
  name: material
  icon:
    logo: material/map
  palette:
    primary: green
extra:
  analytics:
    provider: google
    property: G-55T428V372
plugins:
  - blog
  - social
