site_name: Lost Mapper
site_url: https://lostmapper.com/
site_description: Wandering in the world of map-making, cartography and GIS
site_author: Brian Kelly

copyright: 'Copyright &copy; 2023 Brian Kelly'

theme:
  name: material
  language: en
  icon:
    logo: material/map
  palette:
    primary: green
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  custom_dir: overrides
extra:
  analytics:
    provider: google
    property: G-55T428V372
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@lostmapper
      name: "@lostmapper on YouTube"
    - icon: fontawesome/brands/mastodon
      link: https://mapstodon.space/@lostmapper
      name: "@lostmapper on Mapstodon"
    - icon: fontawesome/brands/github
      link: https://github.com/lostmapper
      name: "lostmapper on GitHub"
    - icon: fontawesome/solid/envelope
      link: mailto:brian@lostmapper.com
      name: "brian@lostmapper.com"
    - icon: fontawesome/solid/mug-saucer
      link: https://ko-fi.com/lostmapper
      name: "Support Me on Ko-Fi"
plugins:
  - blog:
      archive: false
  - social
  - search
  - table-reader
  - gen-files:
      scripts:
        - generate_xyz_tiles.py
markdown_extensions:
  - admonition
nav:
  - index.md
  - blog/index.md
  - "QGIS XYZ Tiles": qgis-xyz-tiles.md
  - resources.md
  - "Tools": https://tools.lostmapper.com
  - about.md